version: '3.8'
services:
  # Node.js Backend Service
  backend:
    build: ./backend
    image: mern-song-app-backend 
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://admin:5V2NuPFfT7yRvsYJ@SG-songs-66516.servers.mongodirector.com:27017/admin

    depends_on:
      - mongo
    networks:
      - mynetwork
    dns:
       - 172.25.16.1
  
  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

# Define named volumes
volumes:
  mongo-data:

# Define networks
networks:
  mynetwork:
