version: '3.8'
services:
  # Node.js Backend Service
  backend:
    build: .
    image: mern-song-app-backend 
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb+srv://Getye:getyepass123@song.eml2d.mongodb.net/?retryWrites=true&w=majority&appName=song
      
    depends_on:
      - mongo
    networks:
      - mynetwork
    dns:
       - 8.8.8.8 # Google DNS
       - 1.1.1.1 # Cloudflare DNS
  
  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

# Define named volumes
volumes:
  mongo-data:

# Define networks
networks:
  mynetwork:
